### ISSUE TITLE
Unable to set sudo password for user.

### ISSUE THREAD

**Issue by krantideep95** [bilguun0203/WSL-ArchLinux#1]
After installation of Arch Linux app, when I open it for the first time, some installation takes place.
After that, username is asked for a new account and an account is created, but no sudo password is set for that user.
So, I am unable to run root commands for that user.
Following [this guide](https://docs.microsoft.com/en-us/windows/wsl/user-support) doesn't help; it throws `'Username' is not in the sudoers file. This incident will be reported.` error on entering correct sudo password. I think I need to run `visudo` and add username according to root's format.

### Workaround: 
- set default user to root. `arch.exe config --default-user root`
- delete user `userdel -r 'username'`
- add user `useradd -m -s /bin/bash 'username'`
- set password using `passwd 'username'`
- set default user to 'username' `arch.exe config --default-user 'username'`

NOTE: after this workaround, you may still be logging into root. Reboot fixed that on my pc.

### System details
Windows 10 Pro version 1803 OS Build : 17133.1

**Comment by bilguun0203** [comment]
I'm currently working on that. And I'm going to publish new version tomorrow.
