### ISSUE TITLE
pacman downloads "corrupted" packages on any command involving "-S" switch

### ISSUE THREAD

**Issue by robinhood2014** [bilguun0203/WSL-ArchLinux#3]
As a rule, when I acquire a new Linux operating system, I make sure to download all available updates prior to using it. In Arch, the command line to do this is "pacman -Syu." Well, unfortunately, when I did that upon first acquiring the WSL-ArchLinux package, it first told me that it couldn't find the correct software keys -- which is strange, because I've always done "pacman -Syu" multiple times on real Arch Linux installations without any problems. Anyway, a simple "pacman-key --init" command fixed that problem, and a subsequent "pacman -Syu" downloaded all the necessary keys.

However, my real issue comes further on down the line in the second "pacman -Syu" command, where it records errors with every single package that it downloaded, complaining that they are all corrupt, and I have to delete them all. This is maddening to me, because a lot of those packages are at the core of every Arch Linux system, and, as I've said before, I've been able to update those packages without any problems on real Arch Linux installs. So why do those corruptions magically happen here, in this WSL package?

**Comment by bilguun0203** [comment]
Hello,
I just tested and works fine for me. Did you do `pacman-key --populate archlinux` command after `pacman-key --init`?
If you are still having a problem, send me your pacman output.

**Comment by robinhood2014** [comment]
Welp. That makes me feel like a dummy. I ran:
`pacman-key --init`
`pacman-key --populate archlinux`
`pacman -Syu`
and that did help to some degree. Sadly, pacman is still marking five packages as corrupt. My newest `pacman -Syu` attempt, after the `checking package integrity` step, returns this:
`error: libseccomp: signature from "Levente Polyak (anthraxx) <levente@leventepolyak.net>" is unknown trust`
`:: File /var/cache/pacman/pkg/libseccomp-2.4.0-1-x86_64.pkg.tar.xz is corrupted (invalid or corrupted package (PGP signature)).`
`Do you want to delete it? [Y/n]`
`error: libssh2: signature from "Levente Polyak (anthraxx) <levente@leventepolyak.net>" is unknown trust`
`:: File /var/cache/pacman/pkg/libssh2-1.8.1-1-x86_64.pkg.tar.xz is corrupted (invalid or corrupted package (PGP signature)).`
`Do you want to delete it? [Y/n]`
`error: libxml2: signature from "Levente Polyak (anthraxx) <levente@leventepolyak.net>" is unknown trust`
`:: File /var/cache/pacman/pkg/libxml2-2.9.9-1-x86_64.pkg.tar.xz is corrupted (invalid or corrupted package (PGP signature)).`
`Do you want to delete it? [Y/n]`
`error: vim-runtime: signature from "Levente Polyak (anthraxx) <levente@leventepolyak.net>" is unknown trust`
`:: File /var/cache/pacman/pkg/vim-runtime-8.1.0996-1-x86_64.pkg.tar.xz is corrupted (invalid or corrupted package (PGP signature)).`
`Do you want to delete it? [Y/n]`
`error: vim: signature from "Levente Polyak (anthraxx) <levente@leventepolyak.net>" is unknown trust`
`:: File /var/cache/pacman/pkg/vim-8.1.0996-1-x86_64.pkg.tar.xz is corrupted (invalid or corrupted package (PGP signature)).`
`Do you want to delete it? [Y/n]`
`error: failed to commit transaction (invalid or corrupted package)`
`Errors occurred, no packages were upgraded.`
Nor can I uninstall any of these affected packages (by doing `pacman -Rns XXX` where `XXX` is a space-separated list of all the affected packages, because it would break dependencies up to and including pacman itself, which would defeat the whole damn purpose of installing this package!

**Comment by bilguun0203** [comment]
Hmm, Try reinstall `archlinux-keyring`, change your pacman mirror in `/etc/pacman.d/mirrorlist`

**Comment by robinhood2014** [comment]
Modifying the pacman mirrorlist didn't seem to help with the next `pacman -Syu` call, but `pacman -S archlinux-keyring` upgraded that single package, and the NEXT `pacman -Syu` call worked!
